### ISSUE TITLE
[Question] Is 1.0.0 faster than 2.x.x? 

### ISSUE THREAD

**Issue by Rad586** [LarsMans64/SeparatedLeaves#3]
From 1.0.0 to 2.x.x version, the mod became data driven. I was wondering if there would be any performance loss?

**Comment by LarsMans64** [comment]
1.0.0 is indeed faster, but the performance impact of 2.0.0 is so small that it would not be noticable at all. Also because leaves only check their distance to logs when a block update happens, instead of every tick, if there would be performance impact, it would only affect one tick which is not a problem in most cases

**Comment by Rad586** [comment]
> 1.0.0 is indeed faster, but the performance impact of 2.0.0 is so small that it would not be noticable at all. Also because leaves only check their distance to logs when a block update happens, instead of every tick, if there would be performance impact, it would only affect one tick which is not a problem in most cases

thanks for replying!
